SET session_replication_role = 'replica';

-- auth_permission (260 rows)
INSERT INTO "auth_permission" ("id", "content_type_id", "codename", "name") VALUES
  (1, 1, 'add_logentry', 'Can add log entry'),
  (2, 1, 'change_logentry', 'Can change log entry'),
  (3, 1, 'delete_logentry', 'Can delete log entry'),
  (4, 1, 'view_logentry', 'Can view log entry'),
  (5, 2, 'add_permission', 'Can add permission'),
  (6, 2, 'change_permission', 'Can change permission'),
  (7, 2, 'delete_permission', 'Can delete permission'),
  (8, 2, 'view_permission', 'Can view permission'),
  (9, 3, 'add_group', 'Can add group'),
  (10, 3, 'change_group', 'Can change group'),
  (11, 3, 'delete_group', 'Can delete group'),
  (12, 3, 'view_group', 'Can view group'),
  (13, 4, 'add_user', 'Can add user'),
  (14, 4, 'change_user', 'Can change user'),
  (15, 4, 'delete_user', 'Can delete user'),
  (16, 4, 'view_user', 'Can view user'),
  (17, 5, 'add_contenttype', 'Can add content type'),
  (18, 5, 'change_contenttype', 'Can change content type'),
  (19, 5, 'delete_contenttype', 'Can delete content type'),
  (20, 5, 'view_contenttype', 'Can view content type'),
  (21, 6, 'add_session', 'Can add session'),
  (22, 6, 'change_session', 'Can change session'),
  (23, 6, 'delete_session', 'Can delete session'),
  (24, 6, 'view_session', 'Can view session'),
  (25, 7, 'add_employee', 'Can add employee'),
  (26, 7, 'change_employee', 'Can change employee'),
  (27, 7, 'delete_employee', 'Can delete employee'),
  (28, 7, 'view_employee', 'Can view employee'),
  (29, 8, 'add_grade', 'Can add grade'),
  (30, 8, 'change_grade', 'Can change grade'),
  (31, 8, 'delete_grade', 'Can delete grade'),
  (32, 8, 'view_grade', 'Can view grade'),
  (33, 9, 'add_school', 'Can add school'),
  (34, 9, 'change_school', 'Can change school'),
  (35, 9, 'delete_school', 'Can delete school'),
  (36, 9, 'view_school', 'Can view school'),
  (37, 10, 'add_subject', 'Can add subject'),
  (38, 10, 'change_subject', 'Can change subject'),
  (39, 10, 'delete_subject', 'Can delete subject'),
  (40, 10, 'view_subject', 'Can view subject'),
  (41, 11, 'add_term', 'Can add term'),
  (42, 11, 'change_term', 'Can change term'),
  (43, 11, 'delete_term', 'Can delete term'),
  (44, 11, 'view_term', 'Can view term'),
  (45, 12, 'add_student', 'Can add student'),
  (46, 12, 'change_student', 'Can change student'),
  (47, 12, 'delete_student', 'Can delete student'),
  (48, 12, 'view_student', 'Can view student'),
  (49, 13, 'add_salary', 'Can add salary'),
  (50, 13, 'change_salary', 'Can change salary'),
  (51, 13, 'delete_salary', 'Can delete salary'),
  (52, 13, 'view_salary', 'Can view salary'),
  (53, 14, 'add_payment', 'Can add payment'),
  (54, 14, 'change_payment', 'Can change payment'),
  (55, 14, 'delete_payment', 'Can delete payment'),
  (56, 14, 'view_payment', 'Can view payment'),
  (57, 15, 'add_leave', 'Can add leave'),
  (58, 15, 'change_leave', 'Can change leave'),
  (59, 15, 'delete_leave', 'Can delete leave'),
  (60, 15, 'view_leave', 'Can view leave'),
  (61, 16, 'add_deduction', 'Can add deduction'),
  (62, 16, 'change_deduction', 'Can change deduction'),
  (63, 16, 'delete_deduction', 'Can delete deduction'),
  (64, 16, 'view_deduction', 'Can view deduction'),
  (65, 17, 'add_assessment', 'Can add assessment'),
  (66, 17, 'change_assessment', 'Can change assessment'),
  (67, 17, 'delete_assessment', 'Can delete assessment'),
  (68, 17, 'view_assessment', 'Can view assessment'),
  (69, 18, 'add_allowance', 'Can add allowance'),
  (70, 18, 'change_allowance', 'Can change allowance'),
  (71, 18, 'delete_allowance', 'Can delete allowance'),
  (72, 18, 'view_allowance', 'Can view allowance'),
  (73, 19, 'add_teacher', 'Can add teacher'),
  (74, 19, 'change_teacher', 'Can change teacher'),
  (75, 19, 'delete_teacher', 'Can delete teacher'),
  (76, 19, 'view_teacher', 'Can view teacher'),
  (77, 20, 'add_schedule', 'Can add schedule'),
  (78, 20, 'change_schedule', 'Can change schedule'),
  (79, 20, 'delete_schedule', 'Can delete schedule'),
  (80, 20, 'view_schedule', 'Can view schedule'),
  (81, 21, 'add_attendance', 'Can add attendance'),
  (82, 21, 'change_attendance', 'Can change attendance'),
  (83, 21, 'delete_attendance', 'Can delete attendance'),
  (84, 21, 'view_attendance', 'Can view attendance'),
  (85, 22, 'add_assessmentresult', 'Can add assessment result'),
  (86, 22, 'change_assessmentresult', 'Can change assessment result'),
  (87, 22, 'delete_assessmentresult', 'Can delete assessment result'),
  (88, 22, 'view_assessmentresult', 'Can view assessment result'),
  (89, 23, 'add_announcement', 'Can add announcement'),
  (90, 23, 'change_announcement', 'Can change announcement'),
  (91, 23, 'delete_announcement', 'Can delete announcement'),
  (92, 23, 'view_announcement', 'Can view announcement'),
  (93, 24, 'add_smsmessage', 'Can add sms message'),
  (94, 24, 'change_smsmessage', 'Can change sms message'),
  (95, 24, 'delete_smsmessage', 'Can delete sms message'),
  (96, 24, 'view_smsmessage', 'Can view sms message'),
  (97, 25, 'add_department', 'Can add department'),
  (98, 25, 'change_department', 'Can change department'),
  (99, 25, 'delete_department', 'Can delete department'),
  (100, 25, 'view_department', 'Can view department'),
  (101, 26, 'add_employeeattendance', 'Can add employee attendance'),
  (102, 26, 'change_employeeattendance', 'Can change employee attendance'),
  (103, 26, 'delete_employeeattendance', 'Can delete employee attendance'),
  (104, 26, 'view_employeeattendance', 'Can view employee attendance'),
  (105, 27, 'add_route', 'Can add route'),
  (106, 27, 'change_route', 'Can change route'),
  (107, 27, 'delete_route', 'Can delete route'),
  (108, 27, 'view_route', 'Can view route'),
  (109, 28, 'add_transportfee', 'Can add transport fee'),
  (110, 28, 'change_transportfee', 'Can change transport fee'),
  (111, 28, 'delete_transportfee', 'Can delete transport fee'),
  (112, 28, 'view_transportfee', 'Can view transport fee'),
  (113, 29, 'add_vehicle', 'Can add vehicle'),
  (114, 29, 'change_vehicle', 'Can change vehicle'),
  (115, 29, 'delete_vehicle', 'Can delete vehicle'),
  (116, 29, 'view_vehicle', 'Can view vehicle'),
  (117, 30, 'add_studenttransportassignment', 'Can add student transport assignment'),
  (118, 30, 'change_studenttransportassignment', 'Can change student transport assignment'),
  (119, 30, 'delete_studenttransportassignment', 'Can delete student transport assignment'),
  (120, 30, 'view_studenttransportassignment', 'Can view student transport assignment'),
  (121, 31, 'add_foodfee', 'Can add food fee'),
  (122, 31, 'change_foodfee', 'Can change food fee'),
  (123, 31, 'delete_foodfee', 'Can delete food fee'),
  (124, 31, 'view_foodfee', 'Can view food fee'),
  (125, 32, 'add_studentfoodassignment', 'Can add student food assignment'),
  (126, 32, 'change_studentfoodassignment', 'Can change student food assignment'),
  (127, 32, 'delete_studentfoodassignment', 'Can delete student food assignment'),
  (128, 32, 'view_studentfoodassignment', 'Can view student food assignment'),
  (129, 33, 'add_foodplan', 'Can add food plan'),
  (130, 33, 'change_foodplan', 'Can change food plan'),
  (131, 33, 'delete_foodplan', 'Can delete food plan'),
  (132, 33, 'view_foodplan', 'Can view food plan'),
  (133, 34, 'add_studentmealpayment', 'Can add student meal payment'),
  (134, 34, 'change_studentmealpayment', 'Can change student meal payment'),
  (135, 34, 'delete_studentmealpayment', 'Can delete student meal payment'),
  (136, 34, 'view_studentmealpayment', 'Can view student meal payment'),
  (137, 35, 'add_mealpricing', 'Can add meal pricing'),
  (138, 35, 'change_mealpricing', 'Can change meal pricing'),
  (139, 35, 'delete_mealpricing', 'Can delete meal pricing'),
  (140, 35, 'view_mealpricing', 'Can view meal pricing'),
  (141, 36, 'add_mealconsumption', 'Can add meal consumption'),
  (142, 36, 'change_mealconsumption', 'Can change meal consumption'),
  (143, 36, 'delete_mealconsumption', 'Can delete meal consumption'),
  (144, 36, 'view_mealconsumption', 'Can view meal consumption'),
  (145, 37, 'add_syncstatus', 'Can add Sync Status'),
  (146, 37, 'change_syncstatus', 'Can change Sync Status'),
  (147, 37, 'delete_syncstatus', 'Can delete Sync Status'),
  (148, 37, 'view_syncstatus', 'Can view Sync Status'),
  (149, 38, 'add_syncqueue', 'Can add sync queue'),
  (150, 38, 'change_syncqueue', 'Can change sync queue'),
  (151, 38, 'delete_syncqueue', 'Can delete sync queue'),
  (152, 38, 'view_syncqueue', 'Can view sync queue'),
  (153, 39, 'add_schoolconfig', 'Can add School Configuration'),
  (154, 39, 'change_schoolconfig', 'Can change School Configuration'),
  (155, 39, 'delete_schoolconfig', 'Can delete School Configuration'),
  (156, 39, 'view_schoolconfig', 'Can view School Configuration'),
  (157, 40, 'add_branch', 'Can add branch'),
  (158, 40, 'change_branch', 'Can change branch'),
  (159, 40, 'delete_branch', 'Can delete branch'),
  (160, 40, 'view_branch', 'Can view branch'),
  (161, 41, 'add_salaryadvance', 'Can add salary advance'),
  (162, 41, 'change_salaryadvance', 'Can change salary advance'),
  (163, 41, 'delete_salaryadvance', 'Can delete salary advance'),
  (164, 41, 'view_salaryadvance', 'Can view salary advance'),
  (165, 42, 'add_leaveapproval', 'Can add leave approval'),
  (166, 42, 'change_leaveapproval', 'Can change leave approval'),
  (167, 42, 'delete_leaveapproval', 'Can delete leave approval'),
  (168, 42, 'view_leaveapproval', 'Can view leave approval'),
  (169, 43, 'add_advanceapproval', 'Can add advance approval'),
  (170, 43, 'change_advanceapproval', 'Can change advance approval'),
  (171, 43, 'delete_advanceapproval', 'Can delete advance approval'),
  (172, 43, 'view_advanceapproval', 'Can view advance approval'),
  (173, 44, 'add_nonteachingstaff', 'Can add Non-Teaching Staff'),
  (174, 44, 'change_nonteachingstaff', 'Can change Non-Teaching Staff'),
  (175, 44, 'delete_nonteachingstaff', 'Can delete Non-Teaching Staff'),
  (176, 44, 'view_nonteachingstaff', 'Can view Non-Teaching Staff'),
  (177, 45, 'add_staffdocument', 'Can add staff document'),
  (178, 45, 'change_staffdocument', 'Can change staff document'),
  (179, 45, 'delete_staffdocument', 'Can delete staff document'),
  (180, 45, 'view_staffdocument', 'Can view staff document'),
  (181, 46, 'add_studentfinanceaccount', 'Can add student finance account'),
  (182, 46, 'change_studentfinanceaccount', 'Can change student finance account'),
  (183, 46, 'delete_studentfinanceaccount', 'Can delete student finance account'),
  (184, 46, 'view_studentfinanceaccount', 'Can view student finance account'),
  (185, 47, 'add_transaction', 'Can add transaction'),
  (186, 47, 'change_transaction', 'Can change transaction'),
  (187, 47, 'delete_transaction', 'Can delete transaction'),
  (188, 47, 'view_transaction', 'Can view transaction'),
  (189, 48, 'add_feestructure', 'Can add fee structure'),
  (190, 48, 'change_feestructure', 'Can change fee structure'),
  (191, 48, 'delete_feestructure', 'Can delete fee structure'),
  (192, 48, 'view_feestructure', 'Can view fee structure'),
  (193, 49, 'add_feecategory', 'Can add fee category'),
  (194, 49, 'change_feecategory', 'Can change fee category'),
  (195, 49, 'delete_feecategory', 'Can delete fee category'),
  (196, 49, 'view_feecategory', 'Can view fee category'),
  (197, 50, 'add_foodsubscription', 'Can add food subscription'),
  (198, 50, 'change_foodsubscription', 'Can change food subscription'),
  (199, 50, 'delete_foodsubscription', 'Can delete food subscription'),
  (200, 50, 'view_foodsubscription', 'Can view food subscription')
ON CONFLICT DO NOTHING;
INSERT INTO "auth_permission" ("id", "content_type_id", "codename", "name") VALUES
  (201, 51, 'add_foodtransaction', 'Can add food transaction'),
  (202, 51, 'change_foodtransaction', 'Can change food transaction'),
  (203, 51, 'delete_foodtransaction', 'Can delete food transaction'),
  (204, 51, 'view_foodtransaction', 'Can view food transaction'),
  (205, 52, 'add_mealitem', 'Can add meal item'),
  (206, 52, 'change_mealitem', 'Can change meal item'),
  (207, 52, 'delete_mealitem', 'Can delete meal item'),
  (208, 52, 'view_mealitem', 'Can view meal item'),
  (209, 53, 'add_foodstudentaccount', 'Can add food student account'),
  (210, 53, 'change_foodstudentaccount', 'Can change food student account'),
  (211, 53, 'delete_foodstudentaccount', 'Can delete food student account'),
  (212, 53, 'view_foodstudentaccount', 'Can view food student account'),
  (213, 54, 'add_route', 'Can add route'),
  (214, 54, 'change_route', 'Can change route'),
  (215, 54, 'delete_route', 'Can delete route'),
  (216, 54, 'view_route', 'Can view route'),
  (217, 55, 'add_transportassignment', 'Can add transport assignment'),
  (218, 55, 'change_transportassignment', 'Can change transport assignment'),
  (219, 55, 'delete_transportassignment', 'Can delete transport assignment'),
  (220, 55, 'view_transportassignment', 'Can view transport assignment'),
  (221, 56, 'add_transportstudentaccount', 'Can add transport student account'),
  (222, 56, 'change_transportstudentaccount', 'Can change transport student account'),
  (223, 56, 'delete_transportstudentaccount', 'Can delete transport student account'),
  (224, 56, 'view_transportstudentaccount', 'Can view transport student account'),
  (225, 57, 'add_transporttransaction', 'Can add transport transaction'),
  (226, 57, 'change_transporttransaction', 'Can change transport transaction'),
  (227, 57, 'delete_transporttransaction', 'Can delete transport transaction'),
  (228, 57, 'view_transporttransaction', 'Can view transport transaction'),
  (229, 58, 'add_transportdriver', 'Can add transport driver'),
  (230, 58, 'change_transportdriver', 'Can change transport driver'),
  (231, 58, 'delete_transportdriver', 'Can delete transport driver'),
  (232, 58, 'view_transportdriver', 'Can view transport driver'),
  (233, 59, 'add_transportvehicle', 'Can add transport vehicle'),
  (234, 59, 'change_transportvehicle', 'Can change transport vehicle'),
  (235, 59, 'delete_transportvehicle', 'Can delete transport vehicle'),
  (236, 59, 'view_transportvehicle', 'Can view transport vehicle'),
  (237, 60, 'add_transportexpense', 'Can add transport expense'),
  (238, 60, 'change_transportexpense', 'Can change transport expense'),
  (239, 60, 'delete_transportexpense', 'Can delete transport expense'),
  (240, 60, 'view_transportexpense', 'Can view transport expense'),
  (241, 61, 'add_transportleaverequest', 'Can add transport leave request'),
  (242, 61, 'change_transportleaverequest', 'Can change transport leave request'),
  (243, 61, 'delete_transportleaverequest', 'Can delete transport leave request'),
  (244, 61, 'view_transportleaverequest', 'Can view transport leave request'),
  (245, 62, 'add_transportadvancerequest', 'Can add transport advance request'),
  (246, 62, 'change_transportadvancerequest', 'Can change transport advance request'),
  (247, 62, 'delete_transportadvancerequest', 'Can delete transport advance request'),
  (248, 62, 'view_transportadvancerequest', 'Can view transport advance request'),
  (249, 63, 'add_salarystructure', 'Can add salary structure'),
  (250, 63, 'change_salarystructure', 'Can change salary structure'),
  (251, 63, 'delete_salarystructure', 'Can delete salary structure'),
  (252, 63, 'view_salarystructure', 'Can view salary structure'),
  (253, 64, 'add_payrollrecord', 'Can add payroll record'),
  (254, 64, 'change_payrollrecord', 'Can change payroll record'),
  (255, 64, 'delete_payrollrecord', 'Can delete payroll record'),
  (256, 64, 'view_payrollrecord', 'Can view payroll record'),
  (257, 65, 'add_expense', 'Can add expense'),
  (258, 65, 'change_expense', 'Can change expense'),
  (259, 65, 'delete_expense', 'Can delete expense'),
  (260, 65, 'view_expense', 'Can view expense')
ON CONFLICT DO NOTHING;

