"""
Django settings for school project.

Generated by 'django-admin startproject' using Django 5.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
from django.contrib.messages import constants as messages

# Load environment variables from .env file if it exists
try:
    from dotenv import load_dotenv
    load_dotenv()
except ImportError:
    pass  # python-dotenv not installed, continue without .env support

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-d8tc3m9u-r3=!4bdc^it^k*-dvqqkh^+&(7d$=61&4nb-g&vsx')

# SECURITY WARNING: don't run with debug turned on in production!
# IMPORTANT: When True, Django stores ALL SQL queries in memory which will crash shared hosting!
DEBUG = os.environ.get('DEBUG', 'False') == 'True'

ALLOWED_HOSTS = [
    'auth-system.bdmis.co.ke',
    'edumanage.bdmis.co.ke',
    'www.edumanage.bdmis.co.ke',
    'uniqo.top',
    'www.uniqo.top',
    'localhost',
    '127.0.0.1',
]

# Add any additional hosts from environment
if os.environ.get('ALLOWED_HOSTS'):
    ALLOWED_HOSTS.extend(os.environ.get('ALLOWED_HOSTS').split(','))



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'whitenoise.runserver_nostatic',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'schools',
    'schools.templatetags',
    'config',
    'widget_tweaks',
    'finance',
    'food',
    'transport',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'schools.middleware.CacheControlMiddleware',  # Add cache headers
    # 'schools.middleware.OfflineDetectionMiddleware',  # Offline detection - Disabled for performance

]

ROOT_URLCONF = 'school.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'templates'),
            os.path.join(BASE_DIR, 'frontend/dist')
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
            ],
        },
    },
]

WSGI_APPLICATION = 'school.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
        'CONN_MAX_AGE': 0,  # Ensure connections are closed immediately to save memory
        'OPTIONS': {
            'timeout': 30,  # Increase timeout for busy periods
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Nairobi'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')  # For collectstatic

# Only include directories that exist
STATICFILES_DIRS = []
static_dir = os.path.join(BASE_DIR, 'static')
if os.path.exists(static_dir):
    STATICFILES_DIRS.append(static_dir)

frontend_dist = os.path.join(BASE_DIR, 'frontend/dist')
if os.path.exists(frontend_dist):
    STATICFILES_DIRS.append(frontend_dist)



MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

#STATIC_URL = '/static/'
#STATICFILES_DIRS = [
#    BASE_DIR / 'school' / 'static',
#]
# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL = '/login/'  # Redirect to frontend login route
LOGIN_REDIRECT_URL = '/dashboard'  # After successful login, redirect here
LOGOUT_REDIRECT_URL = '/login/'  # After logout, redirect here

# Session Configuration
# Use signed cookies to avoid DB/Cache locking during high concurrency
SESSION_ENGINE = 'django.contrib.sessions.backends.signed_cookies'
SESSION_COOKIE_AGE = 1209600

#MEDIA_URL = '/media/'
#MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')
#STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Security settings
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_BROWSER_XSS_FILTER = True
X_FRAME_OPTIONS = 'DENY'
SECURE_CROSS_ORIGIN_OPENER_POLICY = None

# Additional security settings for production
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

# CSRF Trusted Origins for production
CSRF_TRUSTED_ORIGINS = os.environ.get('CSRF_TRUSTED_ORIGINS', '').split(',') if os.environ.get('CSRF_TRUSTED_ORIGINS') else []

# Add production domain to CSRF trusted origins if not in DEBUG mode
if not DEBUG:
    # Add your production domain
    CSRF_TRUSTED_ORIGINS.extend([
    'https://edumanage.bdmis.co.ke',
    'https://www.edumanage.bdmis.co.ke',
    'http://edumanage.bdmis.co.ke',
    'https://auth-system.bdmis.co.ke',
    'http://auth-system.bdmis.co.ke',
    ])

# CSRF Cookie settings
CSRF_COOKIE_HTTPONLY = False  # Allow JavaScript to read CSRF token
CSRF_COOKIE_SAMESITE = 'Lax'
CSRF_USE_SESSIONS = False

# CSP settings
CSP_DEFAULT_SRC = ("'self'",)
CSP_SCRIPT_SRC = (
    "'self'",
    "'unsafe-inline'",
    "'unsafe-eval'",
    "https://cdn.jsdelivr.net",
    "https://code.jquery.com",
    "https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js",
)
CSP_STYLE_SRC = (
    "'self'",
    "'unsafe-inline'",
    "https://cdn.jsdelivr.net",
    "https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css",
)
CSP_FONT_SRC = (
    "'self'",
    "data:",
    "https://cdn.jsdelivr.net",
)
CSP_IMG_SRC = (
    "'self'",
    "data:",
    "https:",
)
CSP_CONNECT_SRC = (
    "'self'",
    "https://maps.googleapis.com",
    "https://*.googleapis.com",
)
CSP_FRAME_SRC = (
    "'self'",
    "https://www.google.com",
    "https://maps.google.com",
    "https://*.google.com",
)

# Email Configuration
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'  # Use SMTP for production, or 'django.core.mail.backends.console.EmailBackend' for development
EMAIL_HOST = 'smtp.gmail.com'  # SMTP server (Gmail: smtp.gmail.com, Outlook: smtp-mail.outlook.com, etc.)
EMAIL_PORT = 587  # Port for TLS (587) or SSL (465)
EMAIL_USE_TLS = True  # Use TLS encryption (True for port 587, False for port 465 with SSL)
EMAIL_HOST_USER = 'keyrooperations@gmail.com'  # Your email address (e.g., noreply@bishopdrmandointernationalschool.org)
EMAIL_HOST_PASSWORD = 'vtao xyut pxzu qzbi'  # Your email password or app-specific password
DEFAULT_FROM_EMAIL = 'keyrooperations@gmail.com'  # Default sender email address

# WhatsApp Business API Configuration (Meta)
WHATSAPP_PHONE_NUMBER_ID = '864197766778782'  # Your WhatsApp Business Phone Number ID
WHATSAPP_ACCESS_TOKEN = 'EAAQWxxIZBvJMBQFkVyRuCNQjsRNdi3MqaqsAh9S6ZBzlPPb8Xp7O4XZCK1WFWySRlj7XknOQvJCT2wkzzg9AfCZBVLmZBJhzx94FHDcjZCvnr7zHjDRIXdF7VAEjrWxuRsVEOl81NZBiRwIHp1wubaQfGG7qwPT3NqwNa9jg8wVvlEWWiMu1ZALFymCiP6ClsYyjgLHDPbUYlEiybE7kQGmHH6C5r5Xg0HqgzmtQdEH9hGqacnmhhdQVe5ZCze9Qjc52GnLux0ZBEUsQsAJkp9lfB514mZC'  # Your WhatsApp Business API Access Token
WHATSAPP_BUSINESS_ACCOUNT_ID = '850700390692147'  # Your WhatsApp Business Account ID
WHATSAPP_API_VERSION = 'v22.0'  # WhatsApp API version (default: v22.0)

# SMS Configuration - Africa's Talking
AFRICASTALKING_USERNAME = 'BDMIS'  # Your Africa's Talking username
AFRICASTALKING_API_KEY = 'atsk_37cc45e2d3f74362b94696e639431088b44599e54fc4eed71dcaeb87632f72a44dbae376'  # Get this from your Africa's Talking dashboard
AFRICASTALKING_ENVIRONMENT = 'production'  # Set to 'production' for live or 'sandbox' for testing
# SMS_SENDER_ID is optional - if not set, Africa's Talking will use default sender ID
# SMS_SENDER_ID = 'BDMIS'  # Uncomment and set your approved sender ID for production

MESSAGE_TAGS = {
    messages.DEBUG: 'info',
    messages.INFO: 'info',
    messages.SUCCESS: 'success',
    messages.WARNING: 'warning',
    messages.ERROR: 'danger',
}


# M-Pesa Configuration
MPESA_ENVIRONMENT = 'sandbox'
MPESA_CONSUMER_KEY = 'svhVXSfDkeudk5abSGKcSh5PAvHq91tMCVj56nAACr20J0Nk'
MPESA_CONSUMER_SECRET = 'dETs62YsA0VxDYqeqwVrD8KGiJnGdjysS5AegESubrR9h65EoDBhum9qlcUlPyo3'
MPESA_SHORTCODE = '174379'  # Standard test shortcode for sandbox
MPESA_PASSKEY = 'bfb279f9aa9bdbcf158e97dd71a467cd2e0c893059b10f78e6b72ada1ed2c919'  # Standard test passkey for sandbox
MPESA_CALLBACK_URL = 'https://api.theransomedschools.org/mpesa/callback/'  # Update this with your actual domain

# Google Maps API Configuration
# Get your API key from: https://console.cloud.google.com/google/maps-apis
# Enable: Maps JavaScript API, Directions API, Geocoding API, Places API
GOOGLE_MAPS_API_KEY = os.environ.get('GOOGLE_MAPS_API_KEY', 'AIzaSyDXwxd0wlWa5pJEBN_glRwD5O2asF9WrHA')


# Update CSP settings
CSP_SCRIPT_SRC = (
    "'self'",
    "'unsafe-inline'",
    "'unsafe-eval'",
    "https://cdn.jsdelivr.net",
    "https://code.jquery.com",
    "https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js",
) 
# WhiteNoise Configuration for Static Files
STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.StaticFilesStorage'

# WhiteNoise settings for better static file serving
WHITENOISE_USE_FINDERS = True  # Allow WhiteNoise to use Django's staticfiles finders
WHITENOISE_AUTOREFRESH = True if DEBUG else False  # Auto-refresh in development
WHITENOISE_MAX_AGE = 31536000 if not DEBUG else 0  # Cache for 1 year in production

# Caching Configuration
# Using FileBasedCache to avoid SQLite locking issues on cPanel
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.filebased.FileBasedCache',
        'LOCATION': os.path.join(BASE_DIR, 'django_cache'),
        'TIMEOUT': 3600,  # 1 hour default timeout
        'OPTIONS': {
            'MAX_ENTRIES': 1000,  # Reduced from 5000 to lower memory usage
            'CULL_FREQUENCY': 3,  # Remove 1/3 of entries when max is reached
        }
    }
}

# Cache key prefix to avoid conflicts
CACHE_MIDDLEWARE_KEY_PREFIX = 'bdmis'
CACHE_MIDDLEWARE_SECONDS = 3600  # Cache pages for 1 hour

# Update MIDDLEWARE to include caching middleware for better performance
# Placing UpdateCacheMiddleware at the beginning and FetchFromCacheMiddleware at the end
# is the standard way to enable site-wide caching, but we'll use per-view caching for more control.

# SSL Proxy Header
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
